spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123
  jpa:
#    database: mysql
    #自动创建更新数据库
    hibernate:
      ddl-auto: update
    show-sql: true

   #freemarker基本配置
  freemarker:
    allow-request-override: false
    request-context-attribute: req
    suffix: .ftl
    content-type=text/html;charset: utf-8
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    number_format: 0.##

file:
  staticAccessPath: /upload/**
  uploadFolder: G://upload/ #文件存放目录











